# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "none"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices
notice = "warn"
# A list of advisory IDs to ignore
ignore = [
    # Add specific advisory IDs to ignore if needed
]

[licenses]
# The confidence threshold for detecting a license from a license text.
confidence-threshold = 0.8
# The lint level for when a license requirement is not satisfied
unlicensed = "deny"
# The lint level for when a license identifier is not recognized
# unrecognized = "deny"  # This key is not valid in current cargo-deny version
# Allow the following licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "MPL-2.0",
]
# Deny the following licenses
deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
# Lint level for when multiple versions of the same license are detected
copyleft = "deny"
# Allow specific license exceptions
allow-osi-fsf-free = "neither"
default = "deny"

[licenses.private]
# If true, ignores workspace crates that aren't published
ignore = false
# One or more registries that you want to ignore sources from
registries = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is '*'
wildcards = "deny"
# The graph highlighting used when creating dotgraphs for crates
highlight = "all"
# The maximum number of versions allowed for a single crate
# multiple-versions-limit = 3  # This key is not valid in current cargo-deny version

# List of crates that are allowed
allow = []

# List of crates to deny
deny = [
    # Deny old openssl versions with known vulnerabilities
    { name = "openssl", version = "<0.10.55" },
    # Deny old tokio versions with known issues
    { name = "tokio", version = "<1.0" },
]

# Certain crates/versions that will be skipped when doing duplicate detection
skip = []

# Similarly to `skip` allows you to skip certain crates from being checked
skip-tree = []

[sources]
# Lint level for what to happen when a crate from a unknown registry is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository is encountered
unknown-git = "warn"
# Allow git sources
allow-git = []

[sources.allow-org]
# 1 or more github.com organizations to allow git sources for
github = []
# 1 or more gitlab.com organizations to allow git sources for
gitlab = []
# 1 or more bitbucket.org organizations to allow git sources for
bitbucket = []